spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maizitoday/springcloud-config.git
          search-paths: projectB
          default-label: master
         