 FROM redis
 EXPOSE  6379


  # 编译 
 # docker build -f /vscode/docker-software-dockerfile/redis/Dockerfile .

 
 # 启动
 # docker run -itd --name redis -v /vscode/docker-software-dockerfile/redis/6379/redis.conf:/etc/redis/redis.conf --privileged  -p 6379:6379  redis

