version: '2'
services:
  namesrv:
    image: rocketmqinc/rocketmq 
    container_name: rmqnamesrv
    ports:
      - 9876:9876 #namesrv只使用了一个9876端口。
    volumes:
      - $PWD/opt/rocketmq/logs:/home/rocketmq/logs
      - $PWD/opt/rocketmq/store:/home/rocketmq/store
    command: nohup sh mqnamesrv &
  broker:
    image: rocketmqinc/rocketmq
    container_name: rmqbroker
    ports:
      - 10909:10909 #主要是fastRemotingServer服务使用
      - 10911:10911 #这个主要是broker的服务端口号，作为对producer和consumer使用服务的端口号，默认为10911，可以通过配置文件中修改。
      - 10912:10912 #slave连接使用
    volumes:
      - $PWD/opt/rocketmq/logs:/home/rocketmq/logs
      - $PWD/opt/rocketmq/store:/home/rocketmq/store
      - $PWD/opt/rocketmq/conf/broker.conf:/opt/rocketmq-4.4.0/conf/broker.conf
    #command: sh mqbroker -n namesrv:9876
    command: nohup sh mqbroker -n namesrv:9876 -c ../conf/broker.conf autoCreateTopicEnable=true  &
    depends_on:
      - namesrv
    environment:
      - JAVA_HOME=/usr/lib/jvm/jre
  console:
    image: styletang/rocketmq-console-ng
    container_name: rocketmq-console-ng
    ports:
      - 8087:8080
    depends_on:
      - namesrv
    environment:
      - JAVA_OPTS= -Dlogging.level.root=info   -Drocketmq.namesrv.addr=rmqnamesrv:9876 
      - Dcom.rocketmq.sendMessageWithVIPChannel=falseclear
