FROM mongo
EXPOSE 27017

#docker hub -- https://hub.docker.com/_/mongo

# 编译
# docker build -t mongo4.2.0 -f /vscode/docker-software-dockerfile/mongodb/Dockerfile .

#  启动
# docker run -p 27017:27017 -v $PWD/27017/db:/data/db -v $PWD/27017/configdb:/data/configdb -d mongo4.2.0

# 用自己的配置文件进行启动
# docker run -p 27017:27017 -v $PWD/27017/db:/data/db -v $PWD/27017/configdb:/data/configdb -d mongo --config /data/configdb/mongod.conf
