server:
  port: 8888
 


spring:
  datasource:
    dynamic:
      primary: mysql #记得设置一个默认数据源
      datasource:
        mysql:
          username: root
          password: root
          url: jdbc:mysql://localhost:3306/maizi?useUnicode=true&characterEncoding=utf-8&noDatetimeStringSync=true
          driver-class-name: com.mysql.cj.jdbc.Driver
        oracle:
          username: SYSTEM
          password: oracle
          url: jdbc:oracle:thin:@localhost:1521:ORCL
          driver-class-name: oracle.jdbc.driver.OracleDriver
         
        
            
     
logging:
  level:
    com: 
      example: 
        mybatisplus:
          user: debug




mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  # configuration:
  #   map-underscore-to-camel-case: true
