server:
  port: 6677


#id：我们自定义的路由 ID，保持唯一
#uri：目标服务地址
#predicates：路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
#filters：过滤规则，本示例暂时没用。

eureka:
  client:
    service-url:
      defaultZone: http://eureka5001.com:5001/eureka,http://eureka5002.com:5002/eureka,http://eureka5003.com:5003/eureka

logging:
  level:
    org.springframework.cloud.gateway: debug

spring:
  application:
    name: cloud-gateway-eureka
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: add_request_parameter_route
          uri: lb://PROVIDE-DATA
          predicates:
            - Path=/**