 FROM logstash:6.8.3
 

# 编译 
# docker build -f /vscode/docker-software-dockerfile/Logstash/Dockerfile .



# 启动   
# docker run --name logstash -itd -p 5044:5044 -v  $PWD/config/logstash.yml:/usr/share/logstash/config/logstash.yml -v $PWD/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml -v $PWD/config/logstash-sample.conf:/usr/share/logstash/config/logstash-sample.conf logstash:6.8.3 







 