spring:
  profiles:
    active:
    - test

---

server:
  port: 8081

spring:
  profiles: dev


---

server:
  port: 8082

spring:
  profiles: test 


#日志文件输入到固定的文件中，这个是当前项目路径
# logging:
#   file: springboot.log


#日志输出到具体的一个目录文件中
logging:
  file: /Users/maizi/Desktop/springboot.log
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n' 
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n' 


