server:
  port: 9001

eureka:
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己,这个也是和提供者的一个区别，这里只是做消费
    service-url:
      defaultZone: http://eureka5001.com:5001/eureka
feign:
  hystrix:
    enabled: true
