

server:
  port: 8002

spring:
  application:
    name: provide-data #入驻eureka的服务名称

eureka:
  client:
    service-url:
      defaultZone: http://eureka5001.com:5001/eureka,http://eureka5002.com:5002/eureka,http://eureka5003.com:5003/eureka